let tagMap = "map"
let tagLocation = "location"
let tagOffsetFromGMT = "offsetFromGMT"
let tagAbbreviation = "abbreviation"

let tagMethodSelectionSection = "methodSelection"
let tagSelectedTimeZoneSection = "selectedTimeZoneSection"

let tagSelectedTimeZone = "selectedTimeZone"
let tagReselect = "reselect"
let tagOK = "ok"

let tagTimeZone = "timeZone"
let tagInfoSection = "infoSection"
let tagName = "name"
let tagDSTInfoSection = "dstInfoSection"
let tagIsDST = "isDST"
let tagDSTOffset = "dstOffset"
let tagNextDSTTransition = "nextDSTTransition"
let tagRefreshInfo = "refreshInfo"

let tagStartDateTime = "startDateTime"
let tagStartTimeZone = "startTimeZone"
let tagEndDateTime = "endDateTime"
let tagEndTimeZone = "endTimeZone"
let tagDaysDiff = "daysDiff"
let tagHoursDiff = "hoursDiff"
let tagMinutesDiff = "minutesDiff"

let tagCurrentTime = "currentTime"
